
-- Drop tables if they already exist
DROP TABLE IF EXISTS RATING;
DROP TABLE IF EXISTS DELIVERY;

DROP TABLE IF EXISTS PAYMENT;

DROP TABLE IF EXISTS ORDER_ITEM;
DROP TABLE IF EXISTS ORDERS;

DROP TABLE IF EXISTS PAYMENT;
	
DROP TABLE IF EXISTS GENERAL_MERCHANDISE;
DROP TABLE IF EXISTS FOOD_BEVERAGE;
DROP TABLE IF EXISTS PRODUCTS;		

DROP TABLE IF EXISTS ADMIN;
DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS USER;

