# Generated by Django 5.1.3 on 2024-11-19 04:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lab9app", "0005_authgroup_authgrouppermissions_authpermission_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Employee",
        ),
    ]
